package com.dsv.pvt.fikafocus;

import com.dsv.pvt.fikafocus.user.User2;
import com.dsv.pvt.fikafocus.user.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

/**
 * localhost:8080/demo/add?name=jane&email=jane@su.se
 *
 */

@Controller // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody String addNewUser (@RequestParam String name
            , @RequestParam String email) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        User2 n = new User2();
        n.setName(name);
        n.setEmail(email);
        userRepository.save(n);
        return "Saved";
    }

        @GetMapping(path="/all")
    public @ResponseBody Iterable<User2> getAllUsers() {
        // This returns a JSON or XML with the users
        return userRepository.findAll();
    }
}
